-- Checklist photos are private. Objects and driver_checklists rows are preserved.
begin;

update storage.buckets
   set public = false
 where id = 'checklist-photos';

drop policy if exists "Acesso público às fotos de checklists"
  on storage.objects;
drop policy if exists "Upload de fotos de checklists"
  on storage.objects;
drop policy if exists checklist_photos_insert_path_guard
  on storage.objects;
drop policy if exists checklist_photos_authenticated_upload
  on storage.objects;
drop policy if exists checklist_photos_anon_insert_deny
  on storage.objects;
drop policy if exists checklist_photos_update_deny
  on storage.objects;
drop policy if exists checklist_photos_delete_deny
  on storage.objects;
drop policy if exists checklist_photos_select_authorized
  on storage.objects;
drop policy if exists checklist_photos_select_scope
  on storage.objects;

-- A restrictive guard keeps legacy permissive policies from widening this bucket.
-- Historical rows contain the exact public URL generated by this Supabase project;
-- new rows contain only the object key. Do not generalize this host comparison.
create policy checklist_photos_insert_scope
on storage.objects as restrictive
for insert
to public
with check (
  bucket_id <> 'checklist-photos'
  or (
    (select auth.uid()) is not null
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and coalesce(array_length(storage.foldername(name), 1), 0) = 1
  )
);

create policy checklist_photos_anon_insert_deny
on storage.objects as restrictive
for insert
to anon
with check (bucket_id <> 'checklist-photos');

create policy checklist_photos_update_delete_deny
on storage.objects as restrictive
for update
to public
using (bucket_id <> 'checklist-photos')
with check (bucket_id <> 'checklist-photos');

create policy checklist_photos_delete_deny
on storage.objects as restrictive
for delete
to public
using (bucket_id <> 'checklist-photos');

create policy checklist_photos_select_scope
on storage.objects as restrictive
for select
to public
using (
  bucket_id <> 'checklist-photos'
  or exists (
    select 1
      from public.driver_checklists as checklist
      join public.profiles as viewer
        on viewer.id = (select auth.uid())
     where checklist.branch_id is not null
       and (
         name = any(checklist.photos)
         or exists (
           select 1
             from unnest(coalesce(checklist.photos, '{}'::text[])) as historical(photo)
            where historical.photo =
              'https://ncliczkwiceoeidfokxk.supabase.co/storage/v1/object/public/checklist-photos/'
              || name
         )
       )
       and viewer.active = true
       and (
         (viewer.role = 'driver'
          and checklist.driver_id = viewer.id
          and (storage.foldername(name))[1] = viewer.id::text)
         or (viewer.role = 'branch_manager'
             and viewer.branch_id = checklist.branch_id)
         or viewer.role in ('fleet_manager', 'admin')
       )
  )
);

create policy checklist_photos_authenticated_upload
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'checklist-photos'
  and (select auth.uid()) is not null
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and coalesce(array_length(storage.foldername(name), 1), 0) = 1
);

create policy checklist_photos_select_authorized
on storage.objects
for select
to authenticated
using (
  bucket_id = 'checklist-photos'
  and exists (
    select 1
      from public.driver_checklists as checklist
      join public.profiles as viewer
        on viewer.id = (select auth.uid())
     where (
       name = any(checklist.photos)
       or exists (
         select 1
           from unnest(coalesce(checklist.photos, '{}'::text[])) as historical(photo)
          where historical.photo =
            'https://ncliczkwiceoeidfokxk.supabase.co/storage/v1/object/public/checklist-photos/'
            || name
       )
     )
       and viewer.active = true
       and (
         (viewer.role = 'driver'
          and checklist.driver_id = viewer.id
          and (storage.foldername(name))[1] = viewer.id::text)
         or (viewer.role = 'branch_manager'
             and viewer.branch_id = checklist.branch_id)
         or viewer.role in ('fleet_manager', 'admin')
       )
  )
);

commit;
